version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: nmikh:spring_boot_docker_test
    build: .

    ports:
      - 9091:8080
    links:
      - mongodb
